index:
  path: /
  controller: App\Controller\DashboardController::renderDashboard
add_site:
  path: /site/add
  controller: App\Controller\SiteController::add
save_site_json:
  path: /site/add/save
  controller: App\Controller\SiteController::saveJson
  methods: [POST]
edit_site:
  path: /site/edit/{slug}
  controller: App\Controller\SiteController::edit
update_site_json:
  path: /site/save
  controller: App\Controller\SiteController::updateJson
  methods: [POST]
crawl_sites:
  path: /sites/crawl
  controller: App\Controller\DashboardController::crawlSites
login:
  path: /login
  controller: App\Controller\SecurityController::login
login_ajax:
  path: /login/ajax
  controller: App\Controller\SecurityController::loginAjax
  methods: [POST]