index:
  path: /
  controller: App\Controller\DashboardController::display
add_site:
  path: /site/new
  controller: App\Controller\DashboardController::new
save_new_site:
  path: /site/new/save
  controller: App\Controller\DashboardController::saveNew
  methods: [POST]
edit_site:
  path: /site/{slug}
  controller: App\Controller\DashboardController::edit
save_site:
  path: /site/{id}/save
  controller: App\Controller\DashboardController::save
  methods: [POST]
crawl_sites:
  path: /sites/crawl
  controller: App\Controller\DashboardController::crawlSites
login:
  path: /login
  controller: App\Controller\SecurityController::login
login_ajax:
  path: /login/ajax
  controller: App\Controller\SecurityController::loginAjax
  methods: [POST]